### PR TITLE
Expand ids

### PR DESCRIPTION
**Pull request by gravesti**
implements #3

### CODE REVIEW

**Comment by gravesti** [comment]
I've added two new options for the data_preparation function to expand data in chunks of patients instead of one by one.
Chunk_size is the number of patients and chunk_expansion to turn it off.

**Review by RoonakR — COMMENTED** [review]
Sorry, but I couldn't really understand how you divide the data! 
I divided data based on id and then expanded each of them.

**Comment by gravesti** [comment]
The main part of the change is this line `j <- split(all_ids, ceiling(seq_along(all_ids)/chunk_size))` which does some integer division to split the ids into chunks of size `chunk_size`.  Then it just follows through your code with a small change to the filtering to handle multiple ids.

The issue with processing them one by one is that we have search and filter the data for each patient, which is quite slow. Fastest is to do the expansion for all patients at once but then we can run out of memory. Using chunks we get a compromise.

**Comment by RoonakR** [comment]
> The main part of the change is this line `j <- split(all_ids, ceiling(seq_along(all_ids)/chunk_size))` which does some integer division to split the ids into chunks of size `chunk_size`. Then it just follows through your code with a small change to the filtering to handle multiple ids.
> 
> The issue with processing them one by one is that we have search and filter the data for each patient, which is quite slow. Fastest is to do the expansion for all patients at once but then we can run out of memory. Using chunks we get a compromise.

Ok! My understanding of the SAS code was that it needs all the data and information from each id for expanding the data but if this also works that's perfect. Thank you for updating the code.

**Pull request merged**
